project_id = "zecybkbqhvozavumzeqp"

[functions.ask-parker]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-resume]
verify_jwt = false

[functions.job-fit-analysis]
verify_jwt = false
